#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions \u0024\u007Bvar\u007D, \u0024\u007Bvar-\u0024\u007Bdefault\u007D\u007D, \u0024\u007Bvar\u002B\u0024\u007Bdefault\u007D\u007D, \u0024\u007Bvar\u003D\u0024\u007Bdefault\u007D\u007D;
#         * compound commands having a testable exit status, especially \u0060case\u0060;
#         * various built-in commands (\u0060command\u0060, \u0060set\u0060, \u0060unalias\u0060, \u0060read\u0060, etc.)
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/subprojects/launcher/src/main/resources/org/gradle/launcher/scripts/gradle.sh
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=\$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=\${app_path%/*}  # leaves a trailing /; empty if no leading path
    [ -h "\$app_path" ]
do
    ls=\$(ls -ld "\$app_path")
    link=\${ls#*-\u003E }
    case \$link in
      /*)   app_path=\$link ;;
      *)    app_path=\$APP_HOME/\$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=\${app_path##*/}
# Discard cd standard output in case \$CDPATH is set https://github.com/gradle/gradle/issues/25036
APP_HOME=\$( cd "\${APP_HOME:-./}" \u0026\u0026 pwd -P 2\u003E/dev/null || exit 1 ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "\$*"
} \u003E\u00262

die () {
    echo
    echo "\$*"
    echo
    exit 1
} \u003E\u00262

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "\$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=\$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "\$JAVA_HOME" ] ; then
    if [ -x "\$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=\$JAVA_HOME/jre/sh/java
    else
        JAVACMD=\$JAVA_HOME/bin/java
    fi
    if [ ! -x "\$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: \$JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java \u003E/dev/null 2\u003E\u00261 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" \u0026\u0026 ! "$darwin" \u0026\u0026 ! "$nonstop" ; then
    case \$MAX_FD in
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=\$(ulimit -H -n) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case \$MAX_FD in
      '' | soft) :;; *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "\$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to \$MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order to eventually pass to $JAVACMD.
#   Some default JVM options, passed as a string, are known to cause problems under POSIX shell.
#   (e.g. parameters with embedded spaces, or pipelines caused by missing quoting)
#   Thus, we split the into separate arguments and prepend to the final arguments list.

# Default JVM options, split into separate arguments
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command;
#   use $JAVACMD basedir and $CLASSPATH to support $0 being a symlink.

# Collect the current set of options that may contain word-splits.
set -- "\$DEFAULT_JVM_OPTS" "\$JAVA_OPTS" "\$GRADLE_OPTS" "\$@"

# Parse JVM arguments and app args, splitting on spaces.
# We have to do this to avoid mixing content with Gradle's own arguments.

# First, extract the JVM arguments and app arguments.
# shellcheck disable=SC2124
APP_ARGS=
while [ "\$#" -gt 0 ]; do
    case "\$1" in
        --app-args)
            # This is an old feature; scripts should use plain arguments instead of --app-args.
            # We shift and continue without adding to APP_ARGS.
            shift
            ;;
        --)
            # Preserve remaining arguments as app args.
            while [ "\$#" -gt 0 ]; do
                APP_ARGS="\$APP_ARGS \$1"
                shift
            done
            ;;
        *)
            # Add to JVM arguments
            JVM_ARGS="\$JVM_ARGS \$1"
            shift
            ;;
    esac
done

# Collect all JVM arguments into one string.
JVM_ARGS="\$JVM_ARGS"

# Prepare the classpath and run.
exec "\$JAVACMD" \$JVM_ARGS -classpath "\$CLASSPATH" org.gradle.wrapper.GradleWrapperMain \$APP_ARGS "\$@"

